### ISSUE TITLE
FreeBuilder on JOOQ generated interfaces produces placeholders.

### ISSUE THREAD

**Issue by eghm** [google/FreeBuilder#119]
Loving the prospect of of being able to generate the builder pattern, thank-you!

When I run FreeBuilder on the interfaces generated using JOOQ (after adding the FreeBuilder annotation and import).  the _Builder.java files are placeholders.  The interfaces (with @FreeBuilder) can be seen here: https://github.com/eghm/EffectiveJavaBuilders/tree/master/db2builder/my-app/src/main/java/com/mycompany/app/jooq/tables/interfaces

The FreeBuilder generated files can be found at https://github.com/eghm/EffectiveJavaBuilders/tree/master/db2builder/my-app/freebuilder-gen/com/mycompany/app/jooq/tables/interfaces

I'm hoping you would be able to shed some light on why I'm not getting full _Builder.java files?

Thank-you for your assistance.

**Comment by cjp39** [comment]
Hey eghm,

You'll need to add a Builder type to each of your interfaces that subclasses the generated buIlder, e.g. in `IAbsent`, add:

    class Builder extends IAbsent_Builder {}

I just checked out the JOOQ manual, and it seems you should be able to configure it to add arbitrary code like this to its generated classes. 👍  If I'm right, it would be great if you could post exact instructions here as I'm sure you won't be the only one wanting to do this!

Thanks!
Chris

**Comment by eghm** [comment]
Thank-you that does indeed resolve my issue.  I'll share the details once I get them sorted.
