### ISSUE TITLE
Bounded type parameters are unbounded in generated code

### ISSUE THREAD

**Issue by JonMerlevede** [google/FreeBuilder#146]
```java
interface Foo { }

@FreeBuilder
interface BuildableType<T extends Foo> {
    T getT();   
    class Builder<T extends Foo> extends BuildableType_Builder<T> {}
}
```

Generates the following code:
```java
@Generated("org.inferred.freebuilder.processor.CodeGenerator")
abstract class BuildableType_Builder<T> {
    ...
}
```
Even though the type parameter `T` in `BuildableType` is bounded, the type `T` in the generated code is unbounded. The generated builder does not work because the type argument `T` in the builder is not within the bounds of the type-variable `T` in `BuildableType`.

**Comment by chrisalice** [comment]
This should now be fixed in [1.10.3](https://github.com/google/FreeBuilder/releases/tag/v1.10.3).
