### ISSUE TITLE
Cannot find checkXXX() methods for checking constraints

### ISSUE THREAD

**Issue by fushar** [google/FreeBuilder#150]
According to the README, this should be generated:

```
@Override void checkAge(int age) {
  // Check single-field (argument) constraints in the check method.
  checkArgument(age >= 0);
}
```

However, I can't find such methods for any of my fields. Am I missing something?

I am using FreeBuilder 1.10.1.

**Comment by chrisalice** [comment]
Sorry, that's a mistake that crept in somehow; I just fixed it. You should override the setter to perform single-field validation. Thanks for the catch!
