### ISSUE TITLE
Generated code statically selects builder from generic child interface

### ISSUE THREAD

**Issue by dminkovsky** [google/FreeBuilder#183]
I have two @FreeBuilder interfaces:

**Child**

```
@FreeBuilder
public interface PIdentityDefinition<T, U> {
    class Builder<T, U> extends PIdentityDefinition_Builder<T, U> {}
}
```

**Parent**

```
@FreeBuilder
public interface PAccess<T, U> {
    class Builder<T, U> extends PAccess_Builder<T, U> {}

    PIdentityDefinition<T, U> getIdentity();
}
```

When I attempt to compile the generated code, I get

```
[ERROR] PAccess_Builder.java:[111,69] cannot select a static class from a parameterized type
[ERROR] PAccess_Builder.java:[125,81] cannot select a static class from a parameterized type
```

where the problem lines looks like

```
111  public PAccess.Builder<T, U> setIdentity(PIdentityDefinition<T, U>.Builder builder) {
112      return setIdentity(builder.build());
113  }
```

```
125  public PAccess.Builder<T, U> mutateIdentity(Consumer<PIdentityDefinition<T, U>.Builder> mutator) {
126      mutator.accept(identity);
127      return (PAccess.Builder<T, U>) this;
128  }
```

As you can see, these two methods select `Builder` from `PIdentityDefinition<T, U>`.

I've played with this a bunch and am not sure how to proceed. This seems to happen because the child class is a `@FreeBuilder` class (I don't think this happens otherwise).

Thank you.

**Comment by dminkovsky** [comment]
So, thankfully I thought of a workaround!

I set the problematic field `Optional<>` which prevents those methods from being generated:

```
@FreeBuilder
public interface PAccess<T, U> {
    class Builder<T, U> extends PAccess_Builder<T, U> {}

    Optional<PIdentityDefinition<T, U>> getIdentity();
}
```

**Comment by dminkovsky** [comment]
Hey @chrisalice, I did not have a chance to look at this before going on vacation this week. My ability to review this may be limited in the coming week.

**Comment by dminkovsky** [comment]
Thank you :D

**Comment by chrisalice** [comment]
By the bye, this was released as [v1.10.5](https://github.com/google/FreeBuilder/releases/tag/v1.10.5).

**Comment by chrisalice** [comment]
Oh, and thanks for the awesome bug report! Made everything really easy 👍

**Comment by dminkovsky** [comment]
Super. Thank you. Sorry I couldn't find time to look at this patch in any
meaningful way. Really appreciate your time on this and you giving me the
opportunity to review. I've been working full time on a personal project
and the GraphQL Java implementation.

вторник, 13 сентября 2016 г. пользователь Chris Purcell написал:
