### ISSUE TITLE
Provide implementation for toString()

### ISSUE THREAD

**Issue by mikekucera** [google/FreeBuilder#186]
I would like the ability to provide my own implementation of toString() for the Value object.
One way to do this would be to provide a lambda which would then be called by toString().

```
class Builder extends Person_Builder {
    public Builder() {
        setName("Fred");
        setToString(person -> "Name: " + person.getName());
    }
}
```

**Comment by chrisalice** [comment]
You should be able to implement `toString()` in your value object. You'll need to make it an abstract class rather than an interface to do this.

```
public abstract class Person {
  
  public abstract String getName();
  public abstract int getAge();

  @Override public String toString() {
    return "Name: " + getName();
  }

  public static class Builder extends Person_Builder {}
}
```

**Comment by mikekucera** [comment]
Great, thanks.
