### ISSUE TITLE
Calling final builder step without providing required arguments

### ISSUE THREAD

**Issue by androidfred** [google/FreeBuilder#196]
STEPS TO REPRODUCE
Call final builder step (usually .build()) without providing required arguments

EXPECTED RESULT
Compiletime error

ACTUAL RESULT
Runtime error

MISC
Instead of returning the builder on all steps, return the next required argument. When there are no required arguments left, return the builder. See eg http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

**Comment by chrisalice** [comment]
That's called a _strict_ builder, and while it has the advantage of compile-time checking, it prevents you building up the object incrementally and breaks the modify-rebuild pattern. However, [Immutables can optionally generate strict builders](https://immutables.github.io/immutable.html#strict-builder) if you still prefer them.
