### ISSUE TITLE
Freebuilder pom declares messy transitive dependencies

### ISSUE THREAD

**Issue by tkruse** [google/FreeBuilder#236]
I get this from gradle dependencies when depending on Freebuilder:
```
     +--- org.inferred:freebuilder:1.12.3
     |    +--- org.apache.commons:commons-lang3:3.4
     |    +--- com.google.googlejavaformat:google-java-format:1.2
     |    |    +--- com.google.guava:guava:19.0
     |    |    \--- com.google.errorprone:javac:9-dev-r3297-1-shaded
     |    +--- com.google.guava:guava:16.0 
     |    \--- com.google.code.findbugs:jsr305:3.0.0
```

* jsr305 should not be in that list at all
* guava is painfully present in 2 different versions

**Comment by chrisalice** [comment]
Quite right, none of those dependencies should be there, since FreeBuilder shades them all. Sorry, I'll try and fix that.

**Comment by chrisalice** [comment]
Incidentally, if you're not already, I recommend using the gradle-processors plugin.

**Comment by tkruse** [comment]
thanks for the tip about gradle-processor, had not seen it. I was using ltgt plugin, but was not too happy with it.

**Comment by chrisalice** [comment]
Note that you *should* be able to work around this issue in the short term by explicitly excluding the transitive dependencies:

```
dependencies {
  processor('org.inferred:freebuilder:1.12.3') {
    exclude group: 'com.google.code.findbugs'
    exclude group: 'com.google.errorprone'
    exclude group: 'com.google.googlejavaformat'
    exclude group: 'com.google.guava'
    exclude group: 'org.apache.commons'
  }
}
```

Though I haven't actually tried, so the snippet may need tweaking.

**Comment by chrisalice** [comment]
Okay, PR #239 fixes this. Google policy prevents me merging and releasing any PR without a review, and I'm unlikely to get anyone's approval until Monday, but in the meantime you can pick up [v1.13.1-rc1](https://github.com/google/FreeBuilder/releases/tag/v1.13.1-rc1).

**Comment by tkruse** [comment]
Thanks. No rush, as you say, there is a workaround (and honestly many projects would not even notice). It's not something that blocked me, just triggered my pedantic nature.
