### ISSUE TITLE
mergeFrom handles NaN defaults incorrectly

### ISSUE THREAD

**Issue by tkruse** [google/FreeBuilder#240]
Findbugs complains that for a class like this:
```
@FreeBuilder
public abstract class Wheel {
    abstract double diameter();
    public static class Builder extends Wheel_Builder {}
}
```
The generated java code contains floating point comparisons for equality:
```
public Wheel.Builder mergeFrom(Wheel value) {
    Wheel_Builder _defaults = new Wheel.Builder();
    if (_defaults._unsetProperties.contains(Wheel_Builder.Property.DIAMETER)
        || value.diameter() != _defaults.diameter()) {
      diameter(value.diameter());
    }
    return (Wheel.Builder) this;
  }
```

Note that both autoValue and Immutable use this code pattern:
```
// autoValue
 return (Double.doubleToLongBits(this.diameter) == Double.doubleToLongBits(that.diameter()));
// Immutables
  private boolean equalTo(ImmutableWheel another) {
    return Double.doubleToLongBits(diameter) == Double.doubleToLongBits(another.diameter);
  }
```

Same for float, I guess.

Also see http://stackoverflow.com/questions/3832592/test-for-floating-point-equality-fe-floating-point-equality

**Comment by tkruse** [comment]
Note that the equals comparison:
´´´
  @Override
    public boolean equals(Object obj) {
      if (!(obj instanceof Wheel_Builder.Value)) {
        return false;
      }
      Wheel_Builder.Value other = (Wheel_Builder.Value) obj;
      return Objects.equals(diameter, other.diameter);
    }
´´´
using Objects.equals() might be suspect to the same vulnerabilities.

**Comment by chrisalice** [comment]
This was an intentional choice when first made, to treat all NaNs as equals. However, `Objects.equals` defers to `Double.equals` which uses `doubleToLongBits`, so we regressed on that decision anyway.

**Comment by chrisalice** [comment]
Lies! Lies! It's just a bug. It'll be exciting trying to write a unit test for this 😄

**Comment by chrisalice** [comment]
Hmmm, doubleToLongBits actually makes all NaNs use the same bit pattern anyway. Not even sure I _can_ write a unit test for this.

**Comment by chrisalice** [comment]
I've remembered the way equality treats NaN backwards. Primitive equality comparison always treats NaNs as not matching. Unit testing should be easy then.

**Comment by chrisalice** [comment]
I'm going to go ahead and delete all my comments, whistle nonchalantly, and pretend this never happened.

**Comment by chrisalice** [comment]
Good spot, thanks! `Object.equals` does the right thing, fortunately.
