### ISSUE TITLE
Questionable downcast

### ISSUE THREAD

**Issue by tkruse** [google/FreeBuilder#241]
Hi, sorry to keep on filling issues, just reporting what Findbugs reports. Can impact other users using Findbugs.
When creating a class with a List member like so:
```
@FreeBuilder
public abstract class Bus extends Vehicle {
    abstract List<Wheel> wheels();
    static class Builder extends Bus_Builder {
    }
}
```
Findbugs complains about the generated code for this downcast to ArayList<?>:
```
 public Bus.Builder addAllWheels(Spliterator<? extends Wheel> elements) {
    if ((elements.characteristics() & Spliterator.SIZED) != 0) {
      long elementsSize = elements.estimateSize();
      if (elementsSize > 0 && elementsSize <= Integer.MAX_VALUE) {
        if (wheels instanceof ImmutableList) {
          wheels = new ArrayList<>(wheels);
        }
        ((ArrayList<?>) wheels).ensureCapacity(wheels.size() + (int) elementsSize);
      }
    }
    elements.forEachRemaining(this::addWheels);
    return (Bus.Builder) this;
  }
```
I assume this code is probably safe, given that we may assume wheels in this case can only be ImmutableList or ArrayList (until Freebuilder implementation changes).

Not sure if this is worth fixing, or what the fix should be.

Note also there is a possible integer overflow case, when wheels.size() + elementsSize > Integer.MAX_VALUE, probably mostly benign, ensureCapacity ignores negative values I think.

**Comment by tkruse** [comment]
Also note that Immutables solves this by not using a List member for the builder, but an inner ImmutableListBuilder.

**Comment by chrisalice** [comment]
This is intentional; it lets us reuse ImmutableList instances when using the modify-rebuild pattern. Using an ImmutableList.Builder would not allow this, and additionally would prevent us offering a get method, or mutate methods.

**Comment by tkruse** [comment]
Well, it's fine not using ImmutableList.Builder, but what about the downcast? Something like this would be equivalent, would it not:
```
-        if (wheels instanceof ImmutableList) {
-          wheels = new ArrayList<>(wheels);
-        }
-        ((ArrayList<?>) wheels).ensureCapacity(wheels.size() + (int) elementsSize);
+     if (wheels instanceof ArrayList) {
+        ((ArrayList<?>) wheels).ensureCapacity(wheels.size() + (int) elementsSize);
+     else {
+          ArrayList wheelsList = new ArrayList<>(wheels);
+          wheelsList.ensureCapacity(wheels.size() + (int) elementsSize);
+          wheels = wheelsList;
+        }
```
This way the downcast is protected.

**Comment by chrisalice** [comment]
Refactoring working code to avoid incorrect Findbugs warnings isn't top of my agenda, I'm afraid 😞  Too much chance of whack-a-mole. If you're willing to experiment and submit a PR, though, I'd be happy to accept a change from `wheels instanceof ImmutableList` to `!(wheels instanceof ArrayList)`.

**Comment by tkruse** [comment]
I won't have time for it, neither. Feel free to close this issue as 'won't fix' from my point of view. I am sure there are workarounds for developers to exclude generated classes from Findbugs checks anyway.

**Comment by chrisalice** [comment]
Okay. Thanks for raising this, regardless.
