### ISSUE TITLE
"Dex cannot parse version 52 byte code" error

### ISSUE THREAD

**Issue by calebdre** [google/FreeBuilder#244]
I've been getting this error when trying to run my project:
```
Dex: Error converting bytecode to dex:
    Cause: Dex cannot parse version 52 byte code.
    This is caused by library dependencies that have been compiled using Java 8 or above.
    If you are using the 'java' gradle plugin in a library submodule add
    targetCompatibility = '1.7'
    sourceCompatibility = '1.7'
```

I've narrowed down all the libraries I use that could cause the error to this one. I'm not super familiar with this, but I'm using retrolambda to be able to use java 8 features. It'd be awesome if I wasn't required to downgrade to use this library! 

Is there a fix for this?

**Comment by chrisalice** [comment]
How are you including the FreeBuilder library? Is it possible dex is picking it up as a dependency? Since it is a compile-only library, it should be ignoring it.

Another possibility to investigate is that retrolambda might not be processing generated code.

**Comment by calebdre** [comment]
I just put it in gradle like in the docs: `compile 'org.inferred:freebuilder:1.14'`  
I just saw that there is more documentation for setting up with intellij - i'll look into those today

**Comment by chrisalice** [comment]
That's your problem, then. I recommend using https://github.com/palantir/gradle-processors, as that will both fix your issue and configure IntelliJ:

```
plugins {
  id 'org.inferred.processors' version '1.2.8'
}

dependencies {
  processor 'org.inferred:freebuilder:1.14'
}
```

**Comment by calebdre** [comment]
@chrisalice I'd like to reopen this issue because it seems like the instructions are for just setting up freebuilder as an annotation processor. Even after doing that, the problem persists.  
  
It says the error stems from the fact that the FreeBuilder is compiled using java 8, and android doesn't like that

**Comment by chrisalice** [comment]
Sounds like a bug in dex, then. Compile-time--only libraries should definitely be ignored.

Can you attach a repro?

**Comment by calebdre** [comment]
I just opening up a new android studio project and added `compile 'org.inferred:freebuilder:1.14'` to the dependencies section of the `app/build.gradle`. If you create a [user](https://github.com/calebdre/observe/blob/master/app/src/main/java/com/observe/observe/entities/User.java) class and compile, everything's great. When trying to deploy, that error shows up

**Comment by aschuurhof** [comment]
This solved it for me. Try using the [android-apt](https://bitbucket.org/hvisser/android-apt) plugin and define your dependency like this:
`apt 'org.inferred:freebuilder:1.14'` and `provided 'org.inferred:freebuilder:1.14'`

**Comment by chrisalice** [comment]
Thanks @aschuurhof!

**Comment by phatnguyenbg** [comment]
Yeah guys 👍 
Today I also got an error like above and below are steps help me resolve problem 💃 
![capture5](https://user-images.githubusercontent.com/29854376/35665407-bc376850-0758-11e8-9ee2-c3ccc8772f39.PNG)
In root (build.gradle) adding: 🥇 
    defaultConfig {
 ...........
 jackOptions {
            enabled true
      }
}
Also adding more this below: 🍡 
 buildTypes { 
.......
}
 compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_7
        targetCompatibility = JavaVersion.VERSION_1_7
    }

Hope this useful for everyone 💯

**Comment by NguyenPhatBG** [comment]
Yeah guys 👍
Today I also got an error like above and below are steps help me resolve problem 💃
capture5
In root (build.gradle) adding: 🥇
defaultConfig {
...........
jackOptions {
enabled true
}
}
Also adding more this below: 🍡
buildTypes {
.......
}
compileOptions {
sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7
}

Hope this useful for everyone 💯
