### ISSUE TITLE
Vote on IntelliJ fix for annotation-processor sources in gradle projects

### ISSUE THREAD

**Issue by tkruse** [google/FreeBuilder#245]
Sorry if this is spam.
IntelliJ IDEA has a bug when trying to import gradle projects using annotation-processor generated sources. I think that may cause users to avoid using FreeBuilder.

Please vote for this to be fixed:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-124090

Close this ticket without further comment if you like.

**Comment by chrisalice** [comment]
Have you tried using the [org.inferred.processors plugin](https://github.com/palantir/gradle-processors)?

**Comment by tkruse** [comment]
Yes, the problem lies entirely with IntelliJ, when using their gradle import. I could get Freebuilder to run by itself and in Eclipse, with and without diverse annotation plugins (also the one you mention). But not in IntelliJ.

IntelliJ with Maven import also works.

My problem is in my team, other developers use IntelliJ, and so I have a hard time introducing FreeBuilder, if every developer will get weird issues.

**Comment by chrisalice** [comment]
The plugin I linked should be fixing IntelliJ's gradle import for you. If it doesn't, we'd greatly appreciate a bug report on the project.

**Comment by tkruse** [comment]
I see. I'll try again to reproduce carefully, then. Might need to wait till next weekend.

**Comment by chrisalice** [comment]
Thanks! If you have issues, please do reopen/raise a new bug.
