### ISSUE TITLE
Person_Builder can not find?

### ISSUE THREAD

**Issue by wanghaile** [google/FreeBuilder#248]
something methods can not find ,ex ,Person_Builder ,setName ... Using the automatically generated program？

**Comment by chrisalice** [comment]
Can you post your code please?

**Comment by wanghaile** [comment]
public interface Person {
    /** Returns this person's full (English) name. */
    String name();
    /** Returns this person's age in years, rounded down. */
    int age();
    /** Returns a new {@link Builder} with the same property values as this person. */
    Builder toBuilder();
    /** Builder of {@link Person} instances. */
    class Builder extends Person_Builder { }
}


when build Person_Builder ?  in my project can not complie  ,is red  in idea

**Comment by chrisalice** [comment]
How did you configure annotation processing in IntelliJ?
