### ISSUE TITLE
Visibility of the generated "Value" and "Partial" class ?

### ISSUE THREAD

**Issue by Gounlaf** [google/FreeBuilder#255]
Hi,

Is there a way to change the visibility of the generated class (Value and Partial), via the annotations or something else?

Thanks,
Regards

**Comment by chrisalice** [comment]
Not currently. What is the use case?

**Comment by Gounlaf** [comment]
Hi @chrisalice,

I would like to use it in Android DialogFragment (support package version).
When running it, I got kind of this error:

`java.lang.IllegalStateException: MyClass.Value must be a public static class to be properly recreated from instance state.`

An example of error + stacktrace can be found here (not me, not with FreeBuilder, but the problem is the same): https://stackoverflow.com/questions/39295458/fragment-must-be-a-public-static-class-to-be-properly-recreated-from-instance-st

**Comment by chrisalice** [comment]
Are you sure just making the class public would be sufficient? I suspect the Builder-accepting constructor would be problematic too.

Suggestions:

1) Copy the java file generated by FreeBuilder to your sources and try changing the visibility by hand, to see if that actually fixes the issue. You may find it just uncovers other problems.
2) Are you annotating your DialogFragment subclass with FreeBuilder? If so, does it work if you move your getters into a stand-alone data class, and store that in your DialogFragment?

**Comment by Gounlaf** [comment]
Hi @chrisalice,

Sorry for the delay; in the meantime I managed my problem without FreeBuilder.
1. I will test it and come back to you (I think it might work)
2. Yes, my subclass was annotated with `@FreeBuilder`; I got kind of error linked previously. But I will try what you suggest too.

Regards

**Comment by chrisalice** [comment]
Closing since I've not heard back from you @Gounlaf, please do reopen if you have any updates
