### ISSUE TITLE
Collection property named 'elements' fails

### ISSUE THREAD

**Issue by tullisar** [google/FreeBuilder#258]
Collection style properties named "elements" defined on a @FreeBuilder annotated class generate code that does not compile. The various `addElements` methods that get generated use the name `elements` as the argument, which causes naming collisions. I figure all that would need to be done is to ensure that references to the backing array list are made with `this` where applicable.

**Comment by chrisalice** [comment]
Thanks for the report, @tullisar. This should be fixed in [v1.14.4](https://github.com/google/FreeBuilder/releases/tag/v1.14.4).
