### ISSUE TITLE
FreeBuilder introduces a potentially conflicting dependency on error_prone_annotations by shading Guava

### ISSUE THREAD

**Issue by orischwartz** [google/FreeBuilder#271]
Introducing FreeBuilder to a Maven build with an existing dependency on an older version Guava can result in the following error:

```
error: cannot access Immutable
  class file for com.google.errorprone.annotations.Immutable not found
1 error
```

The `Immutable` annotation wasn't introduced until [v2.0.6](https://github.com/google/error-prone/commit/2a5759353a04204642b2938bcc9f31a35dfab163#diff-358e33d7e7e09617a48f39da06bf9fe7). So if an application depends on Guava [19.0](https://github.com/google/guava/blob/daa84b68f31898f67a51207e193ee2ddabb088bf/pom.xml#L208-L210) (or some other library with an older error-prone dependency), it'll break.

I don't know if there's a good solution to this but it can be documented. One workaround is to explicitly depend on a compatible version of `error_prone_annotations`.

**Comment by chrisalice** [comment]
That's odd. We shade the Guava dependency explicitly to avoid this kind of issue.

**Comment by orischwartz** [comment]
I was also including an older `error_prone_annotations` through another dependency in [safe-html-types](https://github.com/google/safe-html-types/blob/8507735457ea41a37dfa027fb176d49d5783c4ba/types/pom.xml#L57-L61).

The compilation error was in a project that had a dependency that used FreeBuilder:

1. `A` creates a FreeBuilder type
1. `B` depends on `A` and an older `error_prone_annotations`. 
1. Get compilation error ` class file for com.google.errorprone.annotations.Immutable not found` when compiling `B`

**Comment by chrisalice** [comment]
Presumably you also depend on Guava in A?

**Comment by chrisalice** [comment]
Explicitly, I mean?

**Comment by chrisalice** [comment]
Just checked, and FreeBuilder depends on Guava 16. I think your problem lies elsewhere?

**Comment by orischwartz** [comment]
You are correct, I believe the conflict was with closure-templates declaring its dependency on `error_prone_annotations` as `provided`: https://github.com/google/closure-templates/issues/147

I'm not sure what it was about introducing FreeBuilder that changed Maven's dependency resolution.

Sorry to have you chase this down unnecessarily!

**Comment by chrisalice** [comment]
Glad you figured it out!
