### ISSUE TITLE
Support setFoo(Foo.Builder) for nested buildable types

### ISSUE THREAD

**Issue by fluentfuture** [google/FreeBuilder#45]

**Comment by cjp39** [comment]
I _think_ this is a duplicate of #45, which is fixed but has only just been released as part of 1.0-rc6.

**Comment by cjp39** [comment]
This should be in google3 now. Could you try to reproduce the issue?

**Comment by fluentfuture** [comment]
Just synced. Still can't use setFoo(Builder) or addFoo(Builder).

**Comment by cjp39** [comment]
Could you attach a repro?

**Comment by cjp39** [comment]
Closing as no repro provided. Sorry!
