### ISSUE TITLE
Compliation error when having getTemplate() property

### ISSUE THREAD

**Issue by dorireuv** [google/FreeBuilder#48]
When trying to add a property named template (getTemplate), the generated code doesn't compile because the following line is generated in the clear method:
template = template.template;

Link to the problematic line of code:
https://github.com/google/FreeBuilder/blob/714ba49b21662452ac6cfbc0916500e963ed9d8a/src/main/java/org/inferred/freebuilder/processor/CodeGenerator.java#L351

**Comment by cjp39** [comment]
Thanks, Dori! It just needs a new test in ProcessorTest.java of a value type with a getTemplate() method, to ensure we don't regress in future.
