### ISSUE TITLE
Map putAll generates FindBugs warning

### ISSUE THREAD

**Issue by pgr0ss** [google/FreeBuilder#70]
A field like `public abstract ImmutableMap<String, String> getFields();` generates a method like:

```java
  public My.Builder putAllFields(Map<? extends String, ? extends String> map) {
    for (String key : map.keySet()) {
      putFields(key, map.get(key));
    }
    return (My.Builder) this;
  }
```

FindBugs complains about inefficient use of `keySet()` and `map.get()` instead of `entrySet()`.

I tried to submit a patch, but I had a lot of trouble getting this code running locally. I think you essentially want to change https://github.com/google/FreeBuilder/blob/25fac1babaef8363ea10ddd71b4ee921d1f536b0/src/main/java/org/inferred/freebuilder/processor/MapPropertyFactory.java#L162-L164 to something like:

```java
          .addLine("  for (Map.Entry<%s, %s> entry : map.entrySet()) {", unboxedKeyType.or(keyType), unboxedValueType.or(valueType))
          .addLine("    %s%s(entry.getKey(), entry.getValue());", PUT_PREFIX, property.getCapitalizedName())
          .addLine("  }")
```

**Comment by cjp39** [comment]
This has been released in @FreeBuilder 1.0.1. Thanks, Paul!
